-- MySQL Script generated by MySQL Workbench
-- Fri May 20 20:04:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hoteles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hoteles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Categoría` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Hotel_id` INT NOT NULL,
  `Estrellas` TINYINT NOT NULL,
  `Comentario` TEXT(400) NULL,
  PRIMARY KEY (`id`),
  INDEX `Hotel_id_idx` (`Hotel_id` ASC) VISIBLE,
  CONSTRAINT `Hotel_id`
    FOREIGN KEY (`Hotel_id`)
    REFERENCES `mydb`.`Hoteles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Pertenece_id` INT NOT NULL,
  `Foto` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Hotel_id_idx` (`Pertenece_id` ASC) VISIBLE,
  CONSTRAINT `Pertenece_id`
    FOREIGN KEY (`Pertenece_id`)
    REFERENCES `mydb`.`Hoteles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
